@echo off
rem Fable 5 Physics Sandbox -- written by Claude Fable 5 (Anthropic).
rem MIT License; see LICENSE and README.md.
rem ==========================================================================
rem Rebuild the WebAssembly physics engine after editing physics.cpp.
rem
rem Requires the Emscripten SDK (https://emscripten.org), installed at
rem D:\WebDev\emsdk (git clone + "emsdk install latest" + "emsdk activate
rem latest"). Adjust EMCC below if yours lives elsewhere.
rem
rem Steps: compile physics.cpp to a standalone physics.wasm (no JS glue),
rem then embed it as base64 into physics-wasm-bin.js so the page keeps
rem working when opened directly from disk (file:// cannot fetch .wasm).
rem ==========================================================================
set EMCC=D:\WebDev\emsdk\upstream\emscripten\emcc.exe

%EMCC% physics.cpp -O3 --no-entry -sSTANDALONE_WASM -o physics.wasm || exit /b 1

python -c "import base64; d=base64.b64encode(open('physics.wasm','rb').read()).decode(); open('physics-wasm-bin.js','w').write('// GENERATED by build-wasm.bat -- physics.wasm base64-embedded so the page\n// works from file:// (browsers cannot fetch .wasm from disk). Do not edit.\nconst PHYSICS_WASM_BASE64 =\n' + repr(d) + ';\n')" || exit /b 1

echo Built physics.wasm and physics-wasm-bin.js
